version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
        environment:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
      - image: postgres:12-alpine
        environment:
          POSTGRES_USER: dhos-users
          POSTGRES_PASSWORD: TopSecretPassword
          POSTGRES_DB: "dhos-users"
    steps:
      - checkout
      - run: |
          poetry self update
          poetry config http-basic.sensynehealth ${GEMFURY_DOWNLOAD_KEY} ''
          pip install --upgrade tox
      - run:
          name: Create tox environment
          command: tox -e poetry-install
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Run tox tests
          command: tox -e py39
      - save_cache:
          key: v1-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
  # integration-test:
  #   docker:
  #     - image: cimg/python:3.9
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 20.10.7
  #     - run:
  #         name: Auth with ACR
  #         command: source /usr/local/bin/deployment-helpers-v1.sh; authenticateToACR
  #     - run:
  #         name: Run the integration test script
  #         command: .circleci/run_integration_tests.sh
  deploy-dev:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run:
          name: Add build information
          command: .circleci/record_build_info.sh
      - run:
          name: Build docker image
          command: docker build . -t polaris-users-api --build-arg GEMFURY_DOWNLOAD_KEY
      - run:
          name: Tag docker image
          command: |
            docker tag polaris-users-api ghcr.io/polaris-foundation/polaris-users-api:latest
            docker tag polaris-users-api ghcr.io/polaris-foundation/polaris-users-api:cb-${CIRCLE_BUILD_NUM}
            docker tag polaris-users-api ghcr.io/polaris-foundation/polaris-users-api:$(git log --pretty=format:'%h' -n 1)
      - run:
          name: Authenticate to GHCR
          command: echo $GHCR_TOKEN | docker login ghcr.io -u jonadaly --password-stdin
      - run:
          name: Push docker image
          command: |
            docker push ghcr.io/polaris-foundation/polaris-users-api:latest
            docker push ghcr.io/polaris-foundation/polaris-users-api:cb-${CIRCLE_BUILD_NUM}
            docker push ghcr.io/polaris-foundation/polaris-users-api:$(git log --pretty=format:'%h' -n 1)
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: polaris-foundation
      # - integration-test:
      #     context: engineering-build # Can't run these without publicly available docker images
      - deploy-dev:
          context: polaris-foundation
          requires:
            - test
            # - integration-test
          filters:
            branches:
              only:
                - main
                - setup-cicd # TODO: REMOVE
