@startuml

skinparam defaultFontName Courier

Class User {
    VARCHAR[36]                  ★ uuid                            
    VARCHAR                      ⚪ agency_name                     
    VARCHAR                      ⚪ agency_staff_employee_number    
    BOOLEAN                      ⚪ analytics_consent               
    VARCHAR                      ⚪ booking_reference               
    ARRAY                        ⚪ bookmarked_patients             
    ARRAY                        ⚪ bookmarks                       
    BOOLEAN                      ⚪ can_edit_encounter              
    BOOLEAN                      ⚪ can_edit_ews                    
    DATE                         ⚪ contract_expiry_eod_date        
    DATETIME                     ⚪ created                         
    VARCHAR                      ⚪ created_by_                     
    VARCHAR                      ⚪ email_address                   
    VARCHAR                      ⚪ first_name                      
    ARRAY                        ⚪ groups                          
    VARCHAR                      ⚪ job_title                       
    VARCHAR                      ⚪ last_name                       
    ARRAY                        ⚪ locations                       
    BOOLEAN                      ⚪ login_active                    
    DATETIME                     ⚪ modified                        
    VARCHAR                      ⚪ modified_by_                    
    VARCHAR                      ⚪ nhs_smartcard_number            
    VARCHAR                      ⚪ password_hash                   
    VARCHAR                      ⚪ password_salt                   
    VARCHAR                      ⚪ phone_number                    
    VARCHAR                      ⚪ professional_registration_number
    VARCHAR                      ⚪ send_entry_identifier           
    +                            products                          
    +                            terms_agreement                   
    generate_password_hash()                                       
    set_password()                                                 
    to_auth_dict()                                                 
    to_compact_dict()                                              
    to_dict()                                                      
    to_login_dict()                                                
    update()                                                       
    validate_password()                                            
    INDEX[email_address]         » ix_user_email_address           
    INDEX[first_name]            » ix_user_first_name              
    INDEX[job_title]             » ix_user_job_title               
    INDEX[nhs_smartcard_number]  » ix_user_nhs_smartcard_number    
    INDEX[send_entry_identifier] » ix_user_send_entry_identifier   
}

Class Product {
    VARCHAR[36]    ★ uuid               
    VARCHAR        ☆ user_id            
    DATE           ⚪ closed_date        
    VARCHAR        ⚪ closed_reason      
    VARCHAR        ⚪ closed_reason_other
    DATETIME       ⚪ created            
    VARCHAR        ⚪ created_by_        
    DATETIME       ⚪ modified           
    VARCHAR        ⚪ modified_by_       
    DATE           ⚪ opened_date        
    VARCHAR        ⚪ product_name       
    +              product              
    to_dict()                           
    update()                            
    INDEX[user_id] » ix_product_user_id 
}

Product <--o User: user_id

right footer generated by sadisplay v0.4.9

@enduml
